-- Any number of staff links per role (a second kitchen, a beach bar...),
-- each with its own name, instead of exactly one per role (0015). An extra
-- link sees exactly what its base role sees - staff-access only ever looks
-- at the role, never at which of that role's links was used - so a second
-- "bar" link shows the same bar tickets as the first.
--
-- label is the owner-chosen display name; null means "use the role's
-- default name" (Küche/Bar/...), which is what every link created before
-- this migration keeps.

-- The unique constraint's name was generated by Postgres in 0015, so find
-- it by definition rather than assuming it.
do $$
declare constraint_name text;
begin
  select conname into constraint_name
  from pg_constraint
  where conrelid = 'public.restaurant_access'::regclass
    and contype = 'u'
    and pg_get_constraintdef(oid) = 'UNIQUE (menu_slug, role)';
  if constraint_name is not null then
    execute format('alter table public.restaurant_access drop constraint %I', constraint_name);
  end if;
end $$;

alter table public.restaurant_access
  add column if not exists label text
  check (label is null or char_length(btrim(label)) between 1 and 40);

-- admin.html loads every link of a restaurant at once.
create index if not exists restaurant_access_menu_slug_idx on public.restaurant_access(menu_slug);
